"""Configuration module for CDAD CLI."""

from cdad.config.defaults import (
    SUPPORTED_FRAMEWORKS,
    PHASES,
    ALLOWED_VERIFICATION_METHODS,
    VAGUE_KEYWORDS,
    SPEC_FILES_PATTERN,
    TEST_FILES_PATTERN,
    MEMORY_BANK_FILE,
    DISCOVERY_FILE,
    REVIEW_FILE,
    MERGED_FLAG_FILE,
    FRAMEWORK_DETECTION,
)

__all__ = [
    "SUPPORTED_FRAMEWORKS",
    "PHASES",
    "ALLOWED_VERIFICATION_METHODS",
    "VAGUE_KEYWORDS",
    "SPEC_FILES_PATTERN",
    "TEST_FILES_PATTERN",
    "MEMORY_BANK_FILE",
    "DISCOVERY_FILE",
    "REVIEW_FILE",
    "MERGED_FLAG_FILE",
    "FRAMEWORK_DETECTION",
]
